name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ACR build
        id: acr
        uses: azure/docker-login@v1
        with:
            login-server: azappmanregistry.azurecr.io
            username: ${{ secrets.service_principal }}
            password: ${{ secrets.service_principal_password }}
      - name: Push
        run: |
          docker build . -t azappmanregistry.azurecr.io/tgbot:${{ github.sha }}
          docker push azappmanregistry.azurecr.io/tgbot:${{ github.sha }}
