name: Trigger auto deployment for tgbot

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/tgbot-AutoDeployTrigger-4efef2cd-f0a8-4080-a256-ba20638bb4ed.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: azappmanregistry.azurecr.io
          username: ${{ secrets.TGBOT_REGISTRY_USERNAME }}
          password: ${{ secrets.TGBOT_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: azappmanregistry.azurecr.io/tgbot:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TGBOT_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n tgbot -g appointmentcrawler_group --server azappmanregistry.azurecr.io --username  ${{ secrets.TGBOT_REGISTRY_USERNAME }} --password ${{ secrets.TGBOT_REGISTRY_PASSWORD }}
            az containerapp update -n tgbot -g appointmentcrawler_group --image azappmanregistry.azurecr.io/tgbot:${{ github.sha }}
